# configs/rq1.yaml
model     : "pythia-410m-deduped"
dtype     : "float16"
dataset   : "wikitext103"
layer     : 4
head      : 7
n_prompts : 10000
max_len   : 128
batch     : 32
seed      : 42
out_dir   : "/content/drive/MyDrive/From_LogitLens_To_AttentionLens/results"
