model    : "pythia-410m-deduped"
dtype    : "float16"
dataset  : "wikitext103"
n_prompts: 10000    
max_len  : 128
batch    : 32
seed     : 42
annot_thr: 1.0
fig_scale: 0.5
out_dir  : "/content/drive/MyDrive/From_LogitLens_To_AttentionLens/results"
